oscilloscope:
  ip_address: "192.168.0.90"
  save_path: "/mnt/data/measurements/"

measurement:
  captures: 10
  interval: 1.0  # seconds between captures
  gap: 6.0       # gap of the current setup in mm

channels:
  - number: 1
    scale: 10.0  # Maximum scale 100V
    coupling: "DC"
    display: true
  - number: 2
    scale: 100.0  # Maximum scale 100V
    coupling: "DC"
    display: true
  - number: 3
    scale: 10.0   # Maximum scale 10V
    coupling: "DC"
    display: true

trigger:
  source: 1  # Trigger on channel 1
  level: 1.6  # Changed from 0.5 to 8.0V
  mode: "SING"

# New configurations
timebase:
  scale: 0.000001  # 1ms/div
  offset: 0.000003   # No offset from center

acquisition:
  points: 100000  # 1M points memory depth

experiment: 4 # Experiment setup number 